### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by ImNotStable** [dadus33/ChatItem#116]
```
[20:40:17 WARN]: java.lang.IllegalArgumentException
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.internalCreateSystemChatPacket(PacketEditingChatManager.java:127)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.createSystemChatPacket(PacketEditingChatManager.java:74)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.ComponentNMSManager.writeJson(ComponentNMSManager.java:31)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.IComponentManager.manageItem(IComponentManager.java:55)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.lambda$2(ChatPacketManager.java:190)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[20:40:17 WARN]: java.lang.IllegalArgumentException
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.internalCreateSystemChatPacket(PacketEditingChatManager.java:127)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.createSystemChatPacket(PacketEditingChatManager.java:74)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.ComponentNMSManager.writeJson(ComponentNMSManager.java:31)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.IComponentManager.manageItem(IComponentManager.java:55)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.lambda$2(ChatPacketManager.java:190)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[20:40:17 WARN]: java.lang.IllegalArgumentException
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.internalCreateSystemChatPacket(PacketEditingChatManager.java:127)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.createSystemChatPacket(PacketEditingChatManager.java:74)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.ComponentNMSManager.writeJson(ComponentNMSManager.java:31)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.IComponentManager.manageItem(IComponentManager.java:55)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.lambda$2(ChatPacketManager.java:190)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[20:40:17 WARN]: java.lang.IllegalArgumentException
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:40:17 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:40:17 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.internalCreateSystemChatPacket(PacketEditingChatManager.java:127)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.createSystemChatPacket(PacketEditingChatManager.java:74)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.ComponentNMSManager.writeJson(ComponentNMSManager.java:31)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.IComponentManager.manageItem(IComponentManager.java:55)
[20:40:17 WARN]:        at ChatItem-2.4.9.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.lambda$2(ChatPacketManager.java:190)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:40:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:40:17 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

This server is running Paper version git-Paper-405 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3841722)
Server Plugins (41):
Bukkit Plugins:
AdvancedCrates, ChatColor, ChatItem, Citizens, CitizensCMD, CrazyCrates, CrazyEnchantments, DecentHolograms, eGlow, Essentials, EssentialsDiscord, EssentialsDiscordLink, EssentialsSpawn, EternalTags, FastAsyncWorldEdit, ItemEdit, LiteBans, LuckPerms, MineResetLite, Multiverse-Core, OpenInv, PlaceholderAPI, PlugManX, ProtocolLib, QualityEconomy, Shopkeepers, SkBee, Skript, *skript-placeholders, skript-reflect, spark, SuperVanish, TAB, TradeSystem, Vault, ViaBackwards, ViaRewind, ViaVersion, Vulcan, WorldGuard, WorldGuardExtraFlags

**Comment by Elikill58** [comment]
It were fixed few dev build ago, but now it have been released.
