### ISSUE TITLE
paper 1.12.2 does not load. Error occurred while enabling ChatItem v1.4

### ISSUE THREAD

**Issue by TomLewis** [dadus33/ChatItem#22]
Paper 1.12.2
ChatItem 1.4
config.yml https://gist.github.com/TomLewis/b1cf5fe15fa9bf2f673db17e6bd3c696

This error at startup.

```
[12:54:52] [Server thread/ERROR]: Error occurred while enabling ChatItem v1.4 (Is it up to date?)
java.lang.NoSuchFieldError: LIGHT_GRAY_SHULKER_BOX
	at me.dadus33.chatitem.listeners.ChatPacketListenerV2.<init>(ChatPacketListenerV2.java:46) ~[?:?]
	at me.dadus33.chatitem.ChatItem.onEnable(ChatItem.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Elikill58** [comment]
Hi, what is your plugin list ?

**Comment by Elikill58** [comment]
Sorry for the late. I just checked and it's fixed.
