### ISSUE TITLE
1.19 startup warning: PacketPlayOutChat not found

### ISSUE THREAD

**Issue by zefir-git** [dadus33/ChatItem#41]
```
[10:28:25 WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutChat
[10:28:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[10:28:25 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[10:28:25 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[10:28:25 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[10:28:25 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.utils.PacketUtils.lambda$getNmsClass$0(PacketUtils.java:44)
[10:28:25 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[10:28:25 WARN]:        at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.utils.PacketUtils.getNmsClass(PacketUtils.java:41)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.AdventureComponentGetter.hasConditions(AdventureComponentGetter.java:30)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.<init>(ChatPacketManager.java:69)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.<init>(PacketEditingChatManager.java:26)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.ChatItem.chooseManagers(ChatItem.java:70)
[10:28:25 WARN]:        at ChatItem-2.4.jar//me.dadus33.chatitem.ChatItem.onEnable(ChatItem.java:128)
[10:28:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:28:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:28:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[10:28:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
[10:28:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
[10:28:25 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[10:28:25 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[10:28:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[10:28:25 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[10:28:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[10:28:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
Plugin seems to work correctly nevertheless. ProtocolLib version 5.

**Comment by Elikill58** [comment]
Can you re-download it ? I made ghost update just now
