### ISSUE TITLE
Error when displaying the item 

### ISSUE THREAD

**Issue by Slarof** [dadus33/ChatItem#42]
Server - Pufferfish 1.19
Plugin for chat - Chatty
ProtocolLib - #575

Image: https://media.discordapp.net/attachments/171243756849201153/997498459043139634/2022-07-15_16.41.50.png

Error in the console:
[16:41:39 INFO]: L | 🗡 Vova_Erofeev: My diamond pickaxe Diamond Pickaxe x1
[16:41:39 WARN]: java.lang.IllegalAccessException: Can not set final net.minecraft.network.chat.IChatBaseComponent field net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.a to net.minecraft.network.chat.IChatMutableComponent
[16:41:39 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[16:41:39 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[16:41:39 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[16:41:39 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:799)
[16:41:39 WARN]:        at ChatItem-2.4.2.jar//me.dadus33.chatitem.chatmanager.v1.packets.PacketContent$ContentModifier.write(PacketContent.java:197)
[16:41:39 WARN]:        at ChatItem-2.4.2.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.IChatBaseComponentGetter.writeJson(IChatBaseComponentGetter.java:50)
[16:41:39 WARN]:        at ChatItem-2.4.2.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.lambda$2(ChatPacketManager.java:241)
[16:41:39 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:41:39 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:41:39 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:41:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:41:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:41:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Slarof** [comment]
During the server startup with the plugin "ChatItem-2.4.3-SNAPSHOT" found an error:

[17:23:36 INFO]: [ChatItem] Enabling ChatItem v2.4.3-SNAPSHOT
[17:23:36 INFO]: [ChatItem] Detected server version: v1_19
[17:23:36 WARN]: [ChatItem] ProtocolLib have been detected, but actually, snapshot have issues with chat packet. More informations here: https://github.com/dmulloy2/ProtocolLib/issues/1670.
[17:23:36 WARN]: io.netty.channel.ChannelPipelineException: me.dadus33.chatitem.chatmanager.v1.packets.custom.channel.ChannelInboundHandler is not a @Sharable handler, so can't be added or removed multiple times.
[17:23:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600)
[17:23:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:159)
[17:23:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:358)
[17:23:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:339)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.packets.custom.channel.INC2Channel.lambda$0(INC2Channel.java:38)
[17:23:36 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[17:23:36 WARN]:        at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
[17:23:36 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.ListeningList.forEach(ListeningList.java:59)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.packets.custom.channel.INC2Channel.<init>(INC2Channel.java:36)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.packets.custom.CustomPacketManager.<init>(CustomPacketManager.java:34)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.packets.ChatItemPacketManager.<init>(ChatItemPacketManager.java:22)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.PacketEditingChatManager.<init>(PacketEditingChatManager.java:24)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.ChatItem.chooseManagers(ChatItem.java:70)
[17:23:36 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.ChatItem.onEnable(ChatItem.java:128)
[17:23:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:23:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:23:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[17:23:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
[17:23:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
[17:23:36 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[17:23:36 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:421)
[17:23:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[17:23:36 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1123)
[17:23:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304)
[17:23:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:23:36 INFO]: [ChatItem] Loaded 5 getter for base components.
[17:23:36 INFO]: [ChatItem] Save method founded: b. Use ComponentBuilder's method.
[17:23:36 INFO]: [ChatItem] Manager automatically chosen: PacketEditing (packet), ChatListener (chat)
[17:23:36 INFO]: [ChatItem] Load DiscordSRV support.



=========
When trying to show the item, the same error remains

( Image: https://sun9-86.userapi.com/impf/ngxzCpGai92_ypCqrN9XXtuEzYB7omzXnaUgjA/biDc_hDt01k.jpg?size=1920x1017&quality=95&sign=be96f5366e6f0705f3cb0d5fb47c5022 )

[17:24:56 INFO]: L | 🗡 Vova_Erofeev: My item Diamond Pickaxe x1
[17:24:56 WARN]: java.lang.IllegalAccessException: Can not set final net.minecraft.network.chat.IChatBaseComponent field net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.a to net.minecraft.network.chat.IChatMutableComponent
[17:24:56 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[17:24:56 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[17:24:56 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[17:24:56 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:799)
[17:24:56 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.packets.PacketContent$ContentModifier.write(PacketContent.java:197)
[17:24:56 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.basecomp.hook.IChatBaseComponentGetter.writeJson(IChatBaseComponentGetter.java:59)
[17:24:56 WARN]:        at ChatItem-2.4.3-SNAPSHOT.jar//me.dadus33.chatitem.chatmanager.v1.listeners.ChatPacketManager.lambda$2(ChatPacketManager.java:233)
[17:24:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:24:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:24:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:24:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:24:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:24:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Elikill58** [comment]
Seems to be fixed (can't reproduce)
