### ISSUE TITLE
Folia support for ChatItem?

### ISSUE THREAD

**Issue by YouaJing** [dadus33/ChatItem#78]

**Comment by Elikill58** [comment]
Folia should be supported. If you have issue, you can edit your post to add error logs, or ask on discord. Folia should be supported as spigot and paper

**Comment by Elikill58** [comment]
No answer and no error found

**Comment by YouaJing** [comment]
[12:00:28 INFO]: [ChatItem] Enabling ChatItem v2.4.8
[12:00:28 INFO]: [ChatItem] Detected server version: v1_20
[12:00:28 INFO]: [ChatItem] The plugin ProtocolLib has been detected. Loading Protocollib support ...
[12:00:28 INFO]: [ChatItem] Loaded 4 getter for base components.
[12:00:28 INFO]: [ChatItem] Save method founded: b. Use ComponentBuilder's method.
[12:00:28 INFO]: [ChatItem] Manager automatically chosen: PacketEditing (packet), ChatListener (chat)
[12:00:28 INFO]: [ChatItem] Loaded translation for en_gb.
[12:00:28 ERROR]: Error occurred while enabling ChatItem v2.4.8 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:257) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at me.dadus33.chatitem.ChatItem.onEnable(ChatItem.java:176) ~[ChatItem-2.4.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[12:00:28 INFO]: [ChatItem] Disabling ChatItem v2.4.8
